[project]
name = "intel-dmt-mcp-server"
version = "0.1.0"
description = "MCP server for Intel® Device Management Toolkit (DMT)."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.4",
]
